######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 22 17:07:47 2010
######################################################################


QT=core gui network

TEMPLATE = app
TARGET = 
DEPENDPATH += . resources
INCLUDEPATH += .

# Input
HEADERS += mfm.h
FORMS += mfm.ui
SOURCES += main.cpp mfm.cpp
RESOURCES += resources/resources.qrc
